In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv("/Users/hp/Desktop/group/YearPredictionMSD.txt", header = None)

In [5]:
df.shape

(515345, 91)

In [6]:
df.head()

0         1         2         3         4         5         6         7   \
0  2001  49.94357  21.47114  73.07750   8.74861 -17.40628 -13.09905 -25.01202   
1  2001  48.73215  18.42930  70.32679  12.94636 -10.32437 -24.83777   8.76630   
2  2001  50.95714  31.85602  55.81851  13.41693  -6.57898 -18.54940  -3.27872   
3  2001  48.24750  -1.89837  36.29772   2.58776   0.97170 -26.21683   5.05097   
4  2001  50.97020  42.20998  67.09964   8.46791 -15.85279 -16.81409 -12.48207   

         8         9   ...        81         82        83        84        85  \
0 -12.23257   7.83089  ...  13.01620  -54.40548  58.99367  15.37344   1.11144   
1  -0.92019  18.76548  ...   5.66812  -19.68073  33.04964  42.87836  -9.90378   
2  -2.35035  16.07017  ...   3.03800   26.05866 -50.92779  10.93792  -0.07568   
3 -10.34124   3.55005  ...  34.57337 -171.70734 -16.96705 -46.67617 -12.51516   
4  -9.37636  12.63699  ...   9.92661  -55.95724  64.92712 -17.72522  -1.49237   

         86         87        88         89        90  
0 -23.08793   68.40795  -1.82223  -27.46348   2.26327  
1 -32.22788   70.49388  12.04941   58.43453  26.92061  
2  43.20130 -115.00698  -0.05859   39.67068  -0.66345  
3  82.58061  -72.08993   9.90558  199.62971  18.85382  
4  -7.50035   51.76631   7.88713   55.66926  28.74903  

[5 rows x 91 columns]

In [7]:
df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
     ..
61    0
62    0
63    0
64    0
65    0
66    0
67    0
68    0
69    0
70    0
71    0
72    0
73    0
74    0
75    0
76    0
77    0
78    0
79    0
80    0
81    0
82    0
83    0
84    0
85    0
86    0
87    0
88    0
89    0
90    0
Length: 91, dtype: int64

In [8]:
df.dtypes

0       int64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
12    float64
13    float64
14    float64
15    float64
16    float64
17    float64
18    float64
19    float64
20    float64
21    float64
22    float64
23    float64
24    float64
25    float64
26    float64
27    float64
28    float64
29    float64
       ...   
61    float64
62    float64
63    float64
64    float64
65    float64
66    float64
67    float64
68    float64
69    float64
70    float64
71    float64
72    float64
73    float64
74    float64
75    float64
76    float64
77    float64
78    float64
79    float64
80    float64
81    float64
82    float64
83    float64
84    float64
85    float64
86    float64
87    float64
88    float64
89    float64
90    float64
Length: 91, dtype: object

In [9]:
x = df.iloc[:, 1:].as_matrix()
y = df.iloc[:, 0].as_matrix()

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.
C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [10]:
#data normalization
x = (x - x.min()) / (x.max() - x.min())  # all values now between 0 and 1

In [13]:
x.shape

(515345, 90)

In [14]:
print(x)

[[0.18501372 0.18466046 0.18530075 ... 0.18437145 0.18405331 0.18442214]
 [0.18499869 0.18462272 0.18526662 ... 0.18454356 0.18511907 0.18472807]
 [0.1850263  0.18478931 0.18508662 ... 0.18439333 0.18488626 0.18438583]
 ...
 [0.18495398 0.1845511  0.18391364 ... 0.18431872 0.1850636  0.18429364]
 [0.18494204 0.18479585 0.1843525  ... 0.1846462  0.18457807 0.18488724]
 [0.18503747 0.18512754 0.18472154 ... 0.18432563 0.18479551 0.1845451 ]]


In [17]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7, random_state=111)

In [18]:
learning_rate = 0.001
n_epochs = 5
df.batch_size = 100

In [21]:
# define input labels
x = tf.placeholder(dtype=tf.float32, shape=[None, 90])
# define output labels
y = tf.placeholder(dtype=tf.float32, shape=[None, 1])
# model parameters
w = tf.Variable(tf.zeros([90, 1]))
b = tf.Variable(tf.zeros([1]))

In [22]:
logits = tf.add(tf.matmul(x, w), b)
y_hat = tf.nn.softmax(logits)

In [23]:
epsilon = tf.keras.backend.epsilon()
y_hat_clipped = tf.clip_by_value(y_hat, epsilon, 1 - epsilon)
y_hat_log = tf.log(y_hat_clipped)
cross_entropy = -tf.reduce_sum(y * y_hat_log, axis=1)
loss_f = tf.reduce_mean(cross_entropy)

In [24]:
optimizer = tf.train.GradientDescentOptimizer
optimizer_f = optimizer(learning_rate=learning_rate).minimize(loss_f)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [25]:
predictions_check = tf.equal(tf.argmax(y_hat, 1), tf.argmax(y, 1))
accuracy_f = tf.reduce_mean(tf.cast(predictions_check, tf.float32))

In [28]:
n_batches = int(60000/batch_size)
with tf.Session() as tfs:
    tf.global_variables_initializer().run()
    for epoch in range(n_epochs):
        df.reset_index()
        for batch in range(n_batches):
            x_batch, y_batch = df.next_batch()
            feed_dict={x: x_batch, y: y_batch}
            batch_loss,_ = tfs.run([loss_f, optimizer_f],feed_dict=feed_dict )
            print('Batch loss:{}'.format(batch_loss))

AttributeError: 'DataFrame' object has no attribute 'next_batch'